- name: "containers/install"
  aur:
    name:
      - "buildah"
      - "crun"
      - "docker"
      - "docker-compose"
      - "docker-machine-driver-kvm2"
      - "dnsmasq"
      - "draft-bin"
      - "ebtables"
      - "firewalld"
      - "jsonnet"
      - "k9s"
      - "kaniko"
      - "kubectl"
      - "kubernetes-helm-bin"
      - "libvirt"
      - "minikube"
      - "podman"
      - "skaffold-bin"
      - "skopeo"
    skip_installed: yes


- name: "development/containers/docker/user-group"
  become: yes
  user:
    name: "{{ username }}"
    groups:
      - "docker"
      - "libvirt"
    append: yes

- name: "development/containers/firewalld/service"
  become: yes
  systemd:
    name: "firewalld"
    state: "started"
    enabled: yes
    daemon_reload: yes

- name: "development/containers/libvirtd/service"
  become: yes
  systemd:
    name: "libvirtd"
    state: "started"
    enabled: yes
    daemon_reload: yes

- name: "development/containers/libvirt/network/autostart"
  command: "virsh net-autostart default"
  become: yes

- name: "development/containers/libvirt/network/start"
  command: "virsh net-start default"
  become: yes

- name: "development/containers/docker/service"
  become: yes
  systemd:
    name: "docker"
    state: "started"
    enabled: yes
    daemon_reload: yes

- name: "containers/podman/runtime"
  lineinfile:
    create: yes
    path: "~/.config/containers/libpod.conf"
    regexp: ".*runtime =.*"
    line: "runtime = 'crun'"
