- aur:
    name:
      - "sof-firmware"
    skip_installed: yes

- name: "x1c7/audio/sink"
  become: yes
  create: yes
  lineinfile:
    path: "/etc/pulse/default.pa"
    regexp: ".*module-alsa-sink.*"
    line: "load-module module-alsa-sink device=hw:0,0 channels=4"

- name: "x1c7/audio/source"
  become: yes
  lineinfile:
    create: yes
    path: "/etc/pulse/default.pa"
    regexp: ".*module-alsa-source.*"
    line: "load-module module-alsa-source device=hw:0,6 channels=4"
