- name: "x1c7/disks/partition/boot"
  become: yes
  parted:
    device: "/dev/nvme0n1"
    number: 1
    state: "present"
    part_start: "0%"
    part_end: "2GB"
    flags:
      - "boot"
      - "esp"

- name: "x1c7/disks/partition/boot/filesystem"
  filesystem:
    force: yes
    fstype: "vfat"
    dev: "/dev/nvme0n1p1"
    opts: "-F32"

- name: "x1c7/disks/partition/swap"
  become: yes
  parted:
    device: "/dev/nvme0n1"
    number: 2
    state: "present"
    part_start: "2GB"
    part_end: "20GB"
    flags:
      - "swap"

- name: "x1c7/disks/partition/swap/filesystem"
  filesystem:
    force: yes
    fstype: "swap"
    dev: "/dev/nvme0n1p2"

- name: "x1c7/disks/partition/root"
  become: yes
  parted:
    device: "/dev/nvme0n1"
    number: 3
    state: "present"
    part_start: "20GB"
    part_end: "100%"

- name: "x1c7/disks/partition/root/luks"
  luks_device:
    device: "/dev/nvme0n1p3"
    state: "opened"
    name: "root"
    keyfile: "/tmp/luks-key"


- name: "x1c7/disks/partition/root/filesystem"
  filesystem:
    force: yes
    fstype: "ext4"
    dev: "/dev/nvme0n1p3"

- name: "x1c7/disks/partition/root/mount"
  mount:
    path: /mnt
    src: LABEL=root
    fstype: ext4
    state: present

- name: "x1c7/disks/partition/boot/mount"
  mount:
    path: /mnt/boot
    src: LABEL=boot
    fstype: vfat
    state: present
